export default function getBoot() {
  return {
    es: {
      Home: {
        login: "Iniciar Sesión",
        contact: "Contactanos",
        titleHeader: "Make your travel memoriable"
      }
    },
    en: {
      inputData: {
        email: "Email",
        password: "Password",
        firstName: "First Name",
        lastName: "Last Name",
        phoneNumber: "Phone Number",
        clientID: "Client ID",
        age: "Age",
        gender: "Gender",
        street: "Street",
        state: "State/Province",
        postalCode: "Postal Code",
        city: "City",
        country: "Country",
        cancel: "Cancel",
        save: "Save",
        edit: "Edit",
        date: "Date",
        hour: "Hour",
        comment: "Comment",
        location: "Location",
        payment: "Payment",
        purchase: "Purchase",
        nameStore: "Name Store",
        loginButton: "Log in",
        welcomeText: "Welcome to Venis",
        settings: "Settings",
        logOut: "Log Out"
      },
      profile: {
        profileTitle: "My Profile",
        generalInfo: "General Information",
        additionalInfo: "Additional Information",
        myAppointments: "My Appointments",
        noAppointments: "You Don't Have Appointments",
        askAppointments: "Request an Appointment",
        mySkin: "My Skin Type",
        skinType: "Skin Type",
        mainConcern: "Main Concerns",
        mixedSkin: "Mixed Skin",
        oilySkin: "Oily Skin",
        sensitiveSkin: "Sensitive Skin",
        drySkin: "Dry Skin",
        youngSkin: "Normal Skin",
        acne: "Acne",
        wrinkles: "Wrinkles",
        darkCircles: "Dark Circles",
        pigmentation: "Pigmentation",
        rosacea: "Rosacea",
        appointmentComplete: "Appointment Complete",
        leaveReview: "Leave your Review",
        editAppointment: "Edit Appointment",
        appointmentReview: "Appointment Review",
        titleReview: "Title Review",
        sendReview: "Send Review"
      },
      menuNav: {
        profileMenu: "My Profile",
        paymentMenu: "Payment Information",
        purchaseMenu: "Purchase",
        settingsMenu: "Settings",
        logoutMenu: "log out",
        general: "General",
        payment: "Payment",
        purchase: "Purchase"
      },
      inputSettings: {
        currentPassword: " Current Password",
        newPassword: "New Password",
        repeatPassword: "Repeat New Password",
        deleteImage: "Delete Imagen"
      },
      payment: {
        title: "Payment Information",
        myCards: "My Cards",
        billingAdress: "Billing Address",
        deleteCard: "Delete Card",
        addCard: "Add Card",
        cardType: "Card Type",
        cardNumber: "Card Number",
        nameCard: "Name on Card",
        cvvCode: "CVV Code",
        expiryDate: "Expiry Date"
      },
      purchase: {
        title: "Purchase Information"
      },
      modalEdit: {
        titleModal: "Edit Appointment",
        save: "Save",
        cancel: "Cancel"
      },
      modalReview: {
        titleModal: "Review Appointment",
        titleReview: " Title Review",
        comment: "Comment",
        sendReview: "Send Review"
      },
      modalAddCard: {
        titleModal: "Add Card",
        cardType: "Card Type",
        debitCard: "Debit Card",
        creditCard: "Credit Card",
        cardNumber: "Card Number",
        nameCard: "Name on Card",
        cvvCode: "CVV Code",
        expiryDate: "Expiry Date"
      },
      griddle: {
        id: "ID Client",
        name: "Name",
        pull: "Category",
        last: "Last Name",
        email: "Email",
        phone: "Phone number",
        gender: "Gender",
        info: "Reg Date",
        country: "Country",
        source: "Source",
        funnel: "Funnel",
        agent: "Agent",
        contact: "Last contact",
        status: "Status",
        upload: "Upload",
        download: "Download",
        reload: "Refresh",
        print: "Print",
        orderId: "Order ID",
        orderDate: "Order Date",
        amount: "Amount",
        payment: "Payment Method",
        shipped: "Shipped Method",
        deliveryDate: "Delivery Date",
        deliveryStatus: "Delivery Status",
        action: "Actions",
        notes: "Notes",
        brand: "Brand",
        stock: "Stock",
        size: "Size",
        supplier: "Supplier",
        customer: "Customer",
        crmId: "CRM ID",
        department: "Department",
        transType: "Transaction Type",
        psp: "PSP",
        agentTransaction: "Transaction owner",
        agentCustomer: "Lead owner",
        insertDate: "Insert Date",
        affiliate: "Affiliate",
        remAmount: "Rem Amount",
        totalLeads: "Leads",
        totalFtd: "Total FTD",
        convertion: "Convertion",
        lifeTimeValue: "LTV Aff",
        highPotential: "HP%",
        lowPotential: "LP%",
        username: "Username",
        possition: "Possition",
        details: "Details",
        send: "Send",
        lastTickets: "Last Ticket"
      }
    }
  };
}
